spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  session:
    jdbc:
      table-name: spring_session
    store-type: none
  freemarker:
    cache: false
    suffix: .ftl
    enabled: true
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    suffix: .html